name: Simple Debug Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  debug-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Print Hello World
      run: echo "Hello, GitHub Actions! The workflow is running."

    - name: Show current directory
      run: ls -la

    - name: Show Node.js version
      run: node --version || echo "Node.js is not installed."

    - name: Show Docker version
      run: docker --version || echo "Docker is not installed."
